DEFAULT_SPI_BUS = 0
DEFAULT_SPI_CHIP_SELECT = 0
DEFAULT_FREQUENCY_HZ = 433_420_000
DEFAULT_SYMBOL_RATE = 4_800
DEFAULT_TX_GPIO_BCM = 25
DEFAULT_CAPTURE_TIMEOUT = 10.0
DEFAULT_CAPTURE_FRAMES = 1
DEFAULT_CAPTURE_STORE_MODE = "selected"
DEFAULT_CAPTURE_SELECT_INDEX = 0

CAPTURE_FORMAT = "cc1101-somfy-rts-capture-v1"
PROFILE_FORMAT = "cc1101-somfy-rts-profile-v1"
PROTOCOL_SOMFY_RTS = "somfy-rts"
